<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<EnableWindowsTargeting>true</EnableWindowsTargeting>-->
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>false</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.9.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.9.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <!--<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22621.3233" />-->
    <!--<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22621.0" />-->
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="SharpHook" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
    <!--<PackageReference Include="System.Runtime.InteropServices.WindowsRuntime" Version="4.3.0" />-->
    <!--<PackageReference Include="System.Runtime.WindowsRuntime" Version="4.7.0" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
  </ItemGroup>

</Project>
