// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826103701_ExecutionStepTree")]
    partial class ExecutionStepTree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Core.Models.Database.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Core.Models.Database.DiscordBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RateLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscordBots");
                });

            modelBuilder.Entity("Core.Models.Database.Execution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErrorFlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowStructureHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowId", "CreatedOn");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("Core.Models.Database.ExecutionStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowStepType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoopPass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultLocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultLocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowStepId");

                    b.HasIndex("ExecutionId", "Sequence");

                    b.ToTable("ExecutionSteps");
                });

            modelBuilder.Entity("Core.Models.Database.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSubFlow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("Core.Models.Database.FlowArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitorUniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFlowAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("RatioHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioWidth")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioX")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioY")
                        .HasColumnType("REAL");

                    b.Property<string>("SizingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabMatchOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabMatchValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseClientArea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("ParentFlowAreaId");

                    b.ToTable("FlowAreas");
                });

            modelBuilder.Entity("Core.Models.Database.FlowPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlowAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OffsetMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("RatioX")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioY")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowAreaId");

                    b.HasIndex("FlowId");

                    b.ToTable("FlowPoints");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<string>("ConditionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionTextEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorButtonActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorButtonType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorScrollDirectionType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscordBotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowPointEndId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowStepReferenceEndId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowStepReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowStepType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvokedFlowId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLoopInfinite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPointCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPointEndCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyboardInputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyboardInputType")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoopCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMatches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OcrLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentFlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollIntervalMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultExtractPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunCommandPreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunCommandPresetValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunCommandShell")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunCommandWorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessExitCodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitForMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaitForMillisecondsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordBotId");

                    b.HasIndex("FlowAreaId");

                    b.HasIndex("FlowPointEndId");

                    b.HasIndex("FlowPointId");

                    b.HasIndex("FlowStepReferenceEndId");

                    b.HasIndex("FlowStepReferenceId");

                    b.HasIndex("InvokedFlowId");

                    b.HasIndex("RootId");

                    b.HasIndex("FlowId", "OrderNumber");

                    b.HasIndex("ParentFlowStepId", "OrderNumber");

                    b.ToTable("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStepImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<bool>("AllowMultiScale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthoredFrameHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthoredFrameWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthoredMonitorDpi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthoredMonitorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClickOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ScaleTolerance")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("TemplateImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("TemplateMatchMode")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowStepId");

                    b.ToTable("FlowStepImages");
                });

            modelBuilder.Entity("Core.Models.Database.Execution", b =>
                {
                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("Core.Models.Database.ExecutionStep", b =>
                {
                    b.HasOne("Core.Models.Database.Execution", "Execution")
                        .WithMany("ExecutionSteps")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Database.FlowStep", "FlowStep")
                        .WithMany()
                        .HasForeignKey("FlowStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Execution");

                    b.Navigation("FlowStep");
                });

            modelBuilder.Entity("Core.Models.Database.FlowArea", b =>
                {
                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany("FlowAreas")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Database.FlowArea", "ParentFlowArea")
                        .WithMany("ChildFlowAreas")
                        .HasForeignKey("ParentFlowAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("ParentFlowArea");
                });

            modelBuilder.Entity("Core.Models.Database.FlowPoint", b =>
                {
                    b.HasOne("Core.Models.Database.FlowArea", "FlowArea")
                        .WithMany("FlowPoints")
                        .HasForeignKey("FlowAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany("FlowPoints")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");

                    b.Navigation("FlowArea");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStep", b =>
                {
                    b.HasOne("Core.Models.Database.DiscordBot", "DiscordBot")
                        .WithMany("FlowSteps")
                        .HasForeignKey("DiscordBotId");

                    b.HasOne("Core.Models.Database.FlowArea", "FlowArea")
                        .WithMany("FlowSteps")
                        .HasForeignKey("FlowAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany("FlowSteps")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Database.FlowPoint", "FlowPointEnd")
                        .WithMany("EndFlowSteps")
                        .HasForeignKey("FlowPointEndId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowPoint", "FlowPoint")
                        .WithMany("FlowSteps")
                        .HasForeignKey("FlowPointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowStep", "FlowStepReferenceEnd")
                        .WithMany("FlowStepReferencesEnd")
                        .HasForeignKey("FlowStepReferenceEndId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowStep", "FlowStepReference")
                        .WithMany("FlowStepReferences")
                        .HasForeignKey("FlowStepReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.Flow", "InvokedFlow")
                        .WithMany()
                        .HasForeignKey("InvokedFlowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowStep", "ParentFlowStep")
                        .WithMany("ChildrenFlowSteps")
                        .HasForeignKey("ParentFlowStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DiscordBot");

                    b.Navigation("Flow");

                    b.Navigation("FlowArea");

                    b.Navigation("FlowPoint");

                    b.Navigation("FlowPointEnd");

                    b.Navigation("FlowStepReference");

                    b.Navigation("FlowStepReferenceEnd");

                    b.Navigation("InvokedFlow");

                    b.Navigation("ParentFlowStep");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStepImage", b =>
                {
                    b.HasOne("Core.Models.Database.FlowStep", "FlowStep")
                        .WithMany("FlowStepImages")
                        .HasForeignKey("FlowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowStep");
                });

            modelBuilder.Entity("Core.Models.Database.DiscordBot", b =>
                {
                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.Execution", b =>
                {
                    b.Navigation("ExecutionSteps");
                });

            modelBuilder.Entity("Core.Models.Database.Flow", b =>
                {
                    b.Navigation("FlowAreas");

                    b.Navigation("FlowPoints");

                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowArea", b =>
                {
                    b.Navigation("ChildFlowAreas");

                    b.Navigation("FlowPoints");

                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowPoint", b =>
                {
                    b.Navigation("EndFlowSteps");

                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStep", b =>
                {
                    b.Navigation("ChildrenFlowSteps");

                    b.Navigation("FlowStepImages");

                    b.Navigation("FlowStepReferences");

                    b.Navigation("FlowStepReferencesEnd");
                });
#pragma warning restore 612, 618
        }
    }
}
