// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Core.Models.Database.Execution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckpointStepCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStepPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("Core.Models.Database.ExecutionStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultLocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultLocationY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ExecutionSteps");
                });

            modelBuilder.Entity("Core.Models.Database.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("Core.Models.Database.FlowLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anchor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowSearchAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OffsetMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("RatioX")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("FlowSearchAreaId");

                    b.ToTable("FlowLocations");
                });

            modelBuilder.Entity("Core.Models.Database.FlowSearchArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrowserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstanceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitorUniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFlowSearchAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("RatioHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioWidth")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioX")
                        .HasColumnType("REAL");

                    b.Property<float>("RatioY")
                        .HasColumnType("REAL");

                    b.Property<string>("SizingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabMatchOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabMatchValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseClientArea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("ParentFlowSearchAreaId");

                    b.ToTable("FlowSearchAreas");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<string>("ConditionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorButtonActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorButtonType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorScrollDirectionType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlowId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowLocationEndId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowSearchAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowStepReferenceEndId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowStepReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowStepType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSearchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocationCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocationEndCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLoopInfinite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyboardInputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyboardInputType")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationEndX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationEndY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoopCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LoopOnMultipleFindings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMatches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentFlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollIntervalMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubFlowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateMatchMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaitForMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlowLocationEndId");

                    b.HasIndex("FlowLocationId");

                    b.HasIndex("FlowSearchAreaId");

                    b.HasIndex("FlowStepReferenceEndId");

                    b.HasIndex("FlowStepReferenceId");

                    b.HasIndex("RootId");

                    b.HasIndex("SubFlowId");

                    b.HasIndex("FlowId", "OrderNumber");

                    b.HasIndex("ParentFlowStepId", "OrderNumber");

                    b.ToTable("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStepImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<bool>("AllowMultiScale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthoredFrameHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthoredFrameWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthoredMonitorDpi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthoredMonitorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClickAnchor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClickOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ScaleTolerance")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("TemplateImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("TemplateMatchMode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowStepId");

                    b.ToTable("FlowStepImages");
                });

            modelBuilder.Entity("Core.Models.Database.SubFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SubFlows");
                });

            modelBuilder.Entity("Core.Models.Database.Execution", b =>
                {
                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("Core.Models.Database.ExecutionStep", b =>
                {
                    b.HasOne("Core.Models.Database.Execution", "Execution")
                        .WithMany("ExecutionSteps")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Core.Models.Database.FlowLocation", b =>
                {
                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany("FlowLocations")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Database.FlowSearchArea", "FlowSearchArea")
                        .WithMany("FlowLocations")
                        .HasForeignKey("FlowSearchAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("FlowSearchArea");
                });

            modelBuilder.Entity("Core.Models.Database.FlowSearchArea", b =>
                {
                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany("FlowSearchAreas")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Database.FlowSearchArea", "ParentFlowSearchArea")
                        .WithMany("ChildFlowSearchAreas")
                        .HasForeignKey("ParentFlowSearchAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("ParentFlowSearchArea");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStep", b =>
                {
                    b.HasOne("Core.Models.Database.Flow", "Flow")
                        .WithMany("FlowSteps")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Database.FlowLocation", "FlowLocationEnd")
                        .WithMany("EndFlowSteps")
                        .HasForeignKey("FlowLocationEndId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowLocation", "FlowLocation")
                        .WithMany("FlowSteps")
                        .HasForeignKey("FlowLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowSearchArea", "FlowSearchArea")
                        .WithMany("FlowSteps")
                        .HasForeignKey("FlowSearchAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowStep", "FlowStepReferenceEnd")
                        .WithMany("FlowStepReferencesEnd")
                        .HasForeignKey("FlowStepReferenceEndId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowStep", "FlowStepReference")
                        .WithMany("FlowStepReferences")
                        .HasForeignKey("FlowStepReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.Database.FlowStep", "ParentFlowStep")
                        .WithMany("ChildrenFlowSteps")
                        .HasForeignKey("ParentFlowStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Database.SubFlow", "SubFlow")
                        .WithMany("FlowSteps")
                        .HasForeignKey("SubFlowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Flow");

                    b.Navigation("FlowLocation");

                    b.Navigation("FlowLocationEnd");

                    b.Navigation("FlowSearchArea");

                    b.Navigation("FlowStepReference");

                    b.Navigation("FlowStepReferenceEnd");

                    b.Navigation("ParentFlowStep");

                    b.Navigation("SubFlow");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStepImage", b =>
                {
                    b.HasOne("Core.Models.Database.FlowStep", "FlowStep")
                        .WithMany("FlowStepImages")
                        .HasForeignKey("FlowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowStep");
                });

            modelBuilder.Entity("Core.Models.Database.Execution", b =>
                {
                    b.Navigation("ExecutionSteps");
                });

            modelBuilder.Entity("Core.Models.Database.Flow", b =>
                {
                    b.Navigation("FlowLocations");

                    b.Navigation("FlowSearchAreas");

                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowLocation", b =>
                {
                    b.Navigation("EndFlowSteps");

                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowSearchArea", b =>
                {
                    b.Navigation("ChildFlowSearchAreas");

                    b.Navigation("FlowLocations");

                    b.Navigation("FlowSteps");
                });

            modelBuilder.Entity("Core.Models.Database.FlowStep", b =>
                {
                    b.Navigation("ChildrenFlowSteps");

                    b.Navigation("FlowStepImages");

                    b.Navigation("FlowStepReferences");

                    b.Navigation("FlowStepReferencesEnd");
                });

            modelBuilder.Entity("Core.Models.Database.SubFlow", b =>
                {
                    b.Navigation("FlowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
