namespace Model.Enums
{
    public enum AppSettingsEnum
    {
        MAIN_WINDOW_LEFT,
        MAIN_WINDOW_TOP,
        MAIN_WINDOW_WIDTH,
        MAIN_WINDOW_HEIGHT,
        IS_MAIN_WINDOW_MAXIMIZED,

        SELECTOR_WINDOW_LEFT,
        SELECTOR_WINDOW_TOP,
        SELECTOR_WINDOW_WIDTH,
        SELECTOR_WINDOW_HEIGHT,
        IS_SELECTOR_WINDOW_MAXIMIZED,

        IS_EXECUTION_HISTORY_LOG_ENABLED,
        EXECUTION_HISTORY_LOG_IMAGE_QUALITY,

        IS_THEME_DARK
    }
}
