<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Required for the IDE0005(dead usings) rule to work, by setting it to "true" you tell the compiler: 
         "I want to generate a complete metadata map of my public code to expose to external systems."-->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.4.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
  </ItemGroup>

</Project>
