export const IPC_CHANNELS = {
  // ========== Backend pipe channels =================
  BACKEND_SEND: "BACKEND_SEND",
  BACKEND_RECEIVE: "BACKEND_RECEIVE",
  BACKEND_BROADCAST: "BACKEND_BROADCAST",
  BACKEND_DISCONNECTED: "BACKEND_DISCONNECTED",

  // ========== Overlay (Search-area)  channels ==========
  OVERLAY_OPEN_CAPTURE_WINDOW: "OVERLAY_OPEN_CAPTURE_WINDOW",
  OVERLAY_OPEN_PREVIEW_WINDOW: "OVERLAY_OPEN_PREVIEW_WINDOW",
  OVERLAY_SIGNAL_READY: "OVERLAY_SIGNAL_READY",
  OVERLAY_SIGNAL_CLOSE_WINDOW: "OVERLAY_SIGNAL_CLOSE_WINDOW",

  // ========== Image editor channels ==========
  IMAGE_EDITOR_WINDOW_OPEN: "IMAGE_EDITOR_WINDOW_OPEN",
  IMAGE_EDITOR_WINDOW_READY: "IMAGE_EDITOR_WINDOW_READY",
  IMAGE_EDITOR_RETURN_RESULT_TO_WINDOW: "IMAGE_EDITOR_RETURN_RESULT_TO_WINDOW",
} as const;
