export const IPC_CHANNELS = {
  // ========== Backend pipe channels =================
  BACKEND_SEND: "BACKEND_SEND",
  BACKEND_RECEIVE: "BACKEND_RECEIVE",
  BACKEND_DISCONNECTED: "BACKEND_DISCONNECTED",

  // ========== Search-area overlay channels ==========
  SEARCH_AREA_OPEN: "SEARCH_AREA_OPEN",
  SEARCH_AREA_RESULT: "SEARCH_AREA_RESULT",
  SEARCH_AREA_READY: "SEARCH_AREA_READY",
  SEARCH_AREA_SCREENSHOT: "SEARCH_AREA_SCREENSHOT",

  // ========== Image editor channels ==========
  IMAGE_EDITOR_OPEN: "IMAGE_EDITOR_OPEN",
  IMAGE_EDITOR_RESULT: "IMAGE_EDITOR_RESULT",
  IMAGE_EDITOR_READY: "IMAGE_EDITOR_READY",
} as const;
