export const FlowStepTypeEnum = {
  // System Steps
  WAIT: "WAIT",
  LOOP: "LOOP",
  GO_TO: "GO_TO",
  SYSTEM_COMMAND: "SYSTEM_COMMAND",
  SYSTEM_ACTION: "SYSTEM_ACTION",
  SUB_FLOW: "SUB_FLOW",
  NOTIFY: "NOTIFY",
  END_EXECUTION: "END_EXECUTION",
  MARKER: "MARKER",

  // Input Steps
  CURSOR_DRAG: "CURSOR_DRAG",
  CURSOR_CLICK: "CURSOR_CLICK",
  CURSOR_SCROLL: "CURSOR_SCROLL",
  CURSOR_RELOCATE: "CURSOR_RELOCATE",
  WINDOW_FOCUS: "WINDOW_FOCUS",
  WINDOW_RESIZE: "WINDOW_RESIZE",
  WINDOW_RELOCATE: "WINDOW_RELOCATE",
  KEYBOARD_INPUT: "KEYBOARD_INPUT",

  // Decisions
  SEARCH_IMAGE: "SEARCH_IMAGE",
  SEARCH_TEXT: "SEARCH_TEXT",
  CHECK_VALUE: "CHECK_VALUE",

  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
} as const;

export type FlowStepTypeEnum =
  (typeof FlowStepTypeEnum)[keyof typeof FlowStepTypeEnum];
